GET http://localhost:5000/api/v1/user/course?size=8&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsInVzZXJfaWQiOiIxMjAxMjBmMS01M2JhLTQ4Y2QtYjhiOC05Mzc5OWU5ZmUxYmMiLCJlbWFpbCI6InJlaGFubWF1bDExMUBnbWFpbC5jb20iLCJpYXQiOjE3MjU3ODE2OTAsImV4cCI6MTcyNTg2ODA5MH0.3-4yot0wGO-b2HRfdWeJJna5XeTs3KRWXL8AjMs7NUw
